/* eslint-disable react-refresh/only-export-components */
export * from './Home';
export * from './Feminino';
export * from './Product'
export * from './Card';
export * from './Checkout';
export * from './OrderCompleted';
export * from './OrderFailed';
export * from './Login';
export * from './Register';
export * from './Register'
export * from './Dashboard';
export * from './Masculino'